default:
  mem: 4
  threads: 1
  hrs: 12

methylation:
  methylink:
    mem: 2
    threads: 16
    hrs: 72
  modkit:
    mem: 4
    threads: 16
    hrs: 72

analysis:
  dss:
    mem: 8
    threads: 8
    hrs: 72

assembly:
  canu:
    mem: 10
    threads: 16
    hrs: 72
  yak:
    mem: 8
    threads: 8
    hrs: 72
  hifiasm:
    mem: 14
    threads: 16
    hrs: 72


align:
  sambamba:
    mem: 4
    threads: 8
    hrs: 72
  minimap2:
    mem: 4
    threads: 12
    hrs: 72

variant_call:
  samtools:
    mem: 8
    threads: 4
    hrs: 72
  clair3:
    mem: 2
    threads: 16
    hrs: 72
  longphase:
    mem: 4
    threads: 16
    hrs: 72
  sniffles:
    mem: 4
    threads: 16
    hrs: 72
  bcftools:
    mem: 8
    threads: 1
    hrs: 72
