minimap2:
  version: "2.26"

sambamba:
  version: "1.0.0"

seqtk:
  version: "1.4"

canu:
  version: "2.1.1"

yak:
  version: "0.1"

hifiasm:
  version: "0.19.8"

methylink:
  version: "0.6.0"

modkit:
  version: "0.2.4"

pb-CpG-tools:
  version: "2.3.1"

samtools:
  version: "1.14"

bcftools:
  version: "1.17"

bedtools:
  version: "2.29.2"

sniffles:
  version: "2.0.7"
  trf: True

clair3:
  guppy_model: "r941_prom_sup_g5014"
  version: "1.0.2"
  container: "/net/eichler/vol28/software/containers/clair3/1.0.2/clair3_v1.0.2.sif"

longphase:
  version: "1.5"

dss:
  version: "2.46.0"
  container: "/net/eichler/vol28/software/containers/R/DSS/2.46.0/bioconductor-dss_2.46.0--r42hc0cfd56_0.sif"

ucsc:
  version: "202003"